/**
 * Visual Regression Tests for Colors
 * Auto-generated by generate-vrt-baselines.js
 */

import { test, expect } from '@playwright/test';

const STORYBOOK_URL = 'http://localhost:6006';

async function navigateToStory(page: any, storyId: string, theme = 'light') {
  const url = `${STORYBOOK_URL}/iframe.html?id=${storyId}&viewMode=story&theme=${theme}`;
  await page.goto(url);
  await page.waitForLoadState('networkidle');
  await page.waitForTimeout(500); // Allow animations to settle
}

async function stabilizeVisuals(page: any) {
  // Disable animations and hide variable content
  await page.addStyleTag({
    content: `
      *, *::before, *::after {
        animation-duration: 0s !important;
        transition-duration: 0s !important;
      }
      .loading, .spinner, [data-testid*="loading"] {
        visibility: hidden !important;
      }
    `
  });
}

test.describe('Colors Visual Tests', () => {
  
  test('All Colors - light theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-colors--all-colors', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-colors--all-colors-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('All Colors - dark theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-colors--all-colors', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-colors--all-colors-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  test('Brand Colors - light theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-colors--brand-colors', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-colors--brand-colors-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('Brand Colors - dark theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-colors--brand-colors', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-colors--brand-colors-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  test('Semantic Colors - light theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-colors--semantic-colors', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-colors--semantic-colors-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('Semantic Colors - dark theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-colors--semantic-colors', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-colors--semantic-colors-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  test('Accessibility Guide - light theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-colors--accessibility-guide', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-colors--accessibility-guide-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('Accessibility Guide - dark theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-colors--accessibility-guide', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-colors--accessibility-guide-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  test('Chart Colors - light theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-colors--chart-colors', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-colors--chart-colors-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('Chart Colors - dark theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-colors--chart-colors', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-colors--chart-colors-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
});

// Interactive state tests for key components

