/**
 * Visual Regression Tests for Elevation & Shadows
 * Auto-generated by generate-vrt-baselines.js
 */

import { test, expect } from '@playwright/test';

const STORYBOOK_URL = 'http://localhost:6006';

async function navigateToStory(page: any, storyId: string, theme = 'light') {
  const url = `${STORYBOOK_URL}/iframe.html?id=${storyId}&viewMode=story&theme=${theme}`;
  await page.goto(url);
  await page.waitForLoadState('networkidle');
  await page.waitForTimeout(500); // Allow animations to settle
}

async function stabilizeVisuals(page: any) {
  // Disable animations and hide variable content
  await page.addStyleTag({
    content: `
      *, *::before, *::after {
        animation-duration: 0s !important;
        transition-duration: 0s !important;
      }
      .loading, .spinner, [data-testid*="loading"] {
        visibility: hidden !important;
      }
    `
  });
}

test.describe('Elevation & Shadows Visual Tests', () => {
  
  test('All Elevation Levels - light theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-elevation-shadows--all-elevation-levels', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-elevation-shadows--all-elevation-levels-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('All Elevation Levels - dark theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-elevation-shadows--all-elevation-levels', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-elevation-shadows--all-elevation-levels-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  test('Semantic Elevation - light theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-elevation-shadows--semantic-elevation', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-elevation-shadows--semantic-elevation-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('Semantic Elevation - dark theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-elevation-shadows--semantic-elevation', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-elevation-shadows--semantic-elevation-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  test('Interactive Demo - light theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-elevation-shadows--interactive-demo', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-elevation-shadows--interactive-demo-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('Interactive Demo - dark theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-elevation-shadows--interactive-demo', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-elevation-shadows--interactive-demo-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  test('Usage Guidelines - light theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-elevation-shadows--usage-guidelines', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-elevation-shadows--usage-guidelines-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('Usage Guidelines - dark theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-elevation-shadows--usage-guidelines', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-elevation-shadows--usage-guidelines-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
});

// Interactive state tests for key components

