/**
 * Visual Regression Tests for Grid & Layout
 * Auto-generated by generate-vrt-baselines.js
 */

import { test, expect } from '@playwright/test';

const STORYBOOK_URL = 'http://localhost:6006';

async function navigateToStory(page: any, storyId: string, theme = 'light') {
  const url = `${STORYBOOK_URL}/iframe.html?id=${storyId}&viewMode=story&theme=${theme}`;
  await page.goto(url);
  await page.waitForLoadState('networkidle');
  await page.waitForTimeout(500); // Allow animations to settle
}

async function stabilizeVisuals(page: any) {
  // Disable animations and hide variable content
  await page.addStyleTag({
    content: `
      *, *::before, *::after {
        animation-duration: 0s !important;
        transition-duration: 0s !important;
      }
      .loading, .spinner, [data-testid*="loading"] {
        visibility: hidden !important;
      }
    `
  });
}

test.describe('Grid & Layout Visual Tests', () => {
  
  test('All Grid System - light theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-grid-layout--all-grid-system', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-grid-layout--all-grid-system-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('All Grid System - dark theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-grid-layout--all-grid-system', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-grid-layout--all-grid-system-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  test('Layout Patterns - light theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-grid-layout--layout-patterns', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-grid-layout--layout-patterns-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('Layout Patterns - dark theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-grid-layout--layout-patterns', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-grid-layout--layout-patterns-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  test('Responsive Spacing - light theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-grid-layout--responsive-spacing', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-grid-layout--responsive-spacing-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('Responsive Spacing - dark theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-grid-layout--responsive-spacing', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-grid-layout--responsive-spacing-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  test('Usage Guidelines - light theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-grid-layout--usage-guidelines', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-grid-layout--usage-guidelines-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('Usage Guidelines - dark theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-grid-layout--usage-guidelines', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-grid-layout--usage-guidelines-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
});

// Interactive state tests for key components

