/**
 * Visual Regression Tests for Icons
 * Auto-generated by generate-vrt-baselines.js
 */

import { test, expect } from '@playwright/test';

const STORYBOOK_URL = 'http://localhost:6006';

async function navigateToStory(page: any, storyId: string, theme = 'light') {
  const url = `${STORYBOOK_URL}/iframe.html?id=${storyId}&viewMode=story&theme=${theme}`;
  await page.goto(url);
  await page.waitForLoadState('networkidle');
  await page.waitForTimeout(500); // Allow animations to settle
}

async function stabilizeVisuals(page: any) {
  // Disable animations and hide variable content
  await page.addStyleTag({
    content: `
      *, *::before, *::after {
        animation-duration: 0s !important;
        transition-duration: 0s !important;
      }
      .loading, .spinner, [data-testid*="loading"] {
        visibility: hidden !important;
      }
    `
  });
}

test.describe('Icons Visual Tests', () => {
  
  test('Basic Icon - light theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-icons--basic-icon', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-icons--basic-icon-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('Basic Icon - dark theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-icons--basic-icon', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-icons--basic-icon-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  test('Icon Picker - light theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-icons--icon-picker', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-icons--icon-picker-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('Icon Picker - dark theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-icons--icon-picker', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-icons--icon-picker-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  test('All Icons Browser - light theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-icons--all-icons-browser', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-icons--all-icons-browser-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('All Icons Browser - dark theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-icons--all-icons-browser', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-icons--all-icons-browser-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
});

// Interactive state tests for key components

