/**
 * Visual Regression Tests for Input
 * Auto-generated by generate-vrt-baselines.js
 */

import { test, expect } from '@playwright/test';

const STORYBOOK_URL = 'http://localhost:6006';

async function navigateToStory(page: any, storyId: string, theme = 'light') {
  const url = `${STORYBOOK_URL}/iframe.html?id=${storyId}&viewMode=story&theme=${theme}`;
  await page.goto(url);
  await page.waitForLoadState('networkidle');
  await page.waitForTimeout(500); // Allow animations to settle
}

async function stabilizeVisuals(page: any) {
  // Disable animations and hide variable content
  await page.addStyleTag({
    content: `
      *, *::before, *::after {
        animation-duration: 0s !important;
        transition-duration: 0s !important;
      }
      .loading, .spinner, [data-testid*="loading"] {
        visibility: hidden !important;
      }
    `
  });
}

test.describe('Input Visual Tests', () => {
  
  test('Default - light theme', async ({ page }) => {
    await navigateToStory(page, 'input--default', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'input--default-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('Default - dark theme', async ({ page }) => {
    await navigateToStory(page, 'input--default', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'input--default-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  test('Sizes - light theme', async ({ page }) => {
    await navigateToStory(page, 'input--sizes', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'input--sizes-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('Sizes - dark theme', async ({ page }) => {
    await navigateToStory(page, 'input--sizes', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'input--sizes-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  test('Input Types - light theme', async ({ page }) => {
    await navigateToStory(page, 'input--input-types', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'input--input-types-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('Input Types - dark theme', async ({ page }) => {
    await navigateToStory(page, 'input--input-types', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'input--input-types-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  test('States - light theme', async ({ page }) => {
    await navigateToStory(page, 'input--states', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'input--states-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('States - dark theme', async ({ page }) => {
    await navigateToStory(page, 'input--states', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'input--states-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  test('With Icons - light theme', async ({ page }) => {
    await navigateToStory(page, 'input--with-icons', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'input--with-icons-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('With Icons - dark theme', async ({ page }) => {
    await navigateToStory(page, 'input--with-icons', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'input--with-icons-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  test('Form Examples - light theme', async ({ page }) => {
    await navigateToStory(page, 'input--form-examples', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'input--form-examples-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('Form Examples - dark theme', async ({ page }) => {
    await navigateToStory(page, 'input--form-examples', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'input--form-examples-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  test('Validation Patterns - light theme', async ({ page }) => {
    await navigateToStory(page, 'input--validation-patterns', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'input--validation-patterns-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('Validation Patterns - dark theme', async ({ page }) => {
    await navigateToStory(page, 'input--validation-patterns', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'input--validation-patterns-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
});

// Interactive state tests for key components

test.describe('Input Interactive States', () => {
  test('hover state', async ({ page }) => {
    await navigateToStory(page, 'input--default');
    await stabilizeVisuals(page);
    
    const element = page.locator('input').first();
    await element.hover();
    await page.waitForTimeout(100);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'input--default-hover.png',
      { threshold: 0.2, animations: 'disabled' }
    );
  });
  
  test('focus state', async ({ page }) => {
    await navigateToStory(page, 'input--default');
    await stabilizeVisuals(page);
    
    const element = page.locator('input').first();
    await element.focus();
    await page.waitForTimeout(100);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'input--default-focus.png',
      { threshold: 0.2, animations: 'disabled' }
    );
  });
});
