/**
 * Visual Regression Tests for Navigation
 * Auto-generated by generate-vrt-baselines.js
 */

import { test, expect } from '@playwright/test';

const STORYBOOK_URL = 'http://localhost:6006';

async function navigateToStory(page: any, storyId: string, theme = 'light') {
  const url = `${STORYBOOK_URL}/iframe.html?id=${storyId}&viewMode=story&theme=${theme}`;
  await page.goto(url);
  await page.waitForLoadState('networkidle');
  await page.waitForTimeout(500); // Allow animations to settle
}

async function stabilizeVisuals(page: any) {
  // Disable animations and hide variable content
  await page.addStyleTag({
    content: `
      *, *::before, *::after {
        animation-duration: 0s !important;
        transition-duration: 0s !important;
      }
      .loading, .spinner, [data-testid*="loading"] {
        visibility: hidden !important;
      }
    `
  });
}

test.describe('Navigation Visual Tests', () => {
  
  test('Header Navigation - light theme', async ({ page }) => {
    await navigateToStory(page, 'navigation--header-navigation', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'navigation--header-navigation-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('Header Navigation - dark theme', async ({ page }) => {
    await navigateToStory(page, 'navigation--header-navigation', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'navigation--header-navigation-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  test('Sidebar Navigation - light theme', async ({ page }) => {
    await navigateToStory(page, 'navigation--sidebar-navigation', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'navigation--sidebar-navigation-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('Sidebar Navigation - dark theme', async ({ page }) => {
    await navigateToStory(page, 'navigation--sidebar-navigation', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'navigation--sidebar-navigation-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  test('Breadcrumb Navigation - light theme', async ({ page }) => {
    await navigateToStory(page, 'navigation--breadcrumb-navigation', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'navigation--breadcrumb-navigation-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('Breadcrumb Navigation - dark theme', async ({ page }) => {
    await navigateToStory(page, 'navigation--breadcrumb-navigation', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'navigation--breadcrumb-navigation-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  test('Tab Navigation - light theme', async ({ page }) => {
    await navigateToStory(page, 'navigation--tab-navigation', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'navigation--tab-navigation-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('Tab Navigation - dark theme', async ({ page }) => {
    await navigateToStory(page, 'navigation--tab-navigation', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'navigation--tab-navigation-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  test('Mobile Navigation - light theme', async ({ page }) => {
    await navigateToStory(page, 'navigation--mobile-navigation', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'navigation--mobile-navigation-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('Mobile Navigation - dark theme', async ({ page }) => {
    await navigateToStory(page, 'navigation--mobile-navigation', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'navigation--mobile-navigation-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  test('Figma Specifications - light theme', async ({ page }) => {
    await navigateToStory(page, 'navigation--figma-specifications', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'navigation--figma-specifications-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('Figma Specifications - dark theme', async ({ page }) => {
    await navigateToStory(page, 'navigation--figma-specifications', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'navigation--figma-specifications-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
});

// Interactive state tests for key components

