/**
 * Visual Regression Tests for Select
 * Auto-generated by generate-vrt-baselines.js
 */

import { test, expect } from '@playwright/test';

const STORYBOOK_URL = 'http://localhost:6006';

async function navigateToStory(page: any, storyId: string, theme = 'light') {
  const url = `${STORYBOOK_URL}/iframe.html?id=${storyId}&viewMode=story&theme=${theme}`;
  await page.goto(url);
  await page.waitForLoadState('networkidle');
  await page.waitForTimeout(500); // Allow animations to settle
}

async function stabilizeVisuals(page: any) {
  // Disable animations and hide variable content
  await page.addStyleTag({
    content: `
      *, *::before, *::after {
        animation-duration: 0s !important;
        transition-duration: 0s !important;
      }
      .loading, .spinner, [data-testid*="loading"] {
        visibility: hidden !important;
      }
    `
  });
}

test.describe('Select Visual Tests', () => {
  
  test('Default - light theme', async ({ page }) => {
    await navigateToStory(page, 'select--default', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'select--default-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('Default - dark theme', async ({ page }) => {
    await navigateToStory(page, 'select--default', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'select--default-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  test('Business Services - light theme', async ({ page }) => {
    await navigateToStory(page, 'select--business-services', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'select--business-services-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('Business Services - dark theme', async ({ page }) => {
    await navigateToStory(page, 'select--business-services', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'select--business-services-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
});

// Interactive state tests for key components

test.describe('Select Interactive States', () => {
  test('hover state', async ({ page }) => {
    await navigateToStory(page, 'select--default');
    await stabilizeVisuals(page);
    
    const element = page.locator('select').first();
    await element.hover();
    await page.waitForTimeout(100);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'select--default-hover.png',
      { threshold: 0.2, animations: 'disabled' }
    );
  });
  
  test('focus state', async ({ page }) => {
    await navigateToStory(page, 'select--default');
    await stabilizeVisuals(page);
    
    const element = page.locator('select').first();
    await element.focus();
    await page.waitForTimeout(100);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'select--default-focus.png',
      { threshold: 0.2, animations: 'disabled' }
    );
  });
});
