/**
 * Visual Regression Tests for Spacing
 * Auto-generated by generate-vrt-baselines.js
 */

import { test, expect } from '@playwright/test';

const STORYBOOK_URL = 'http://localhost:6006';

async function navigateToStory(page: any, storyId: string, theme = 'light') {
  const url = `${STORYBOOK_URL}/iframe.html?id=${storyId}&viewMode=story&theme=${theme}`;
  await page.goto(url);
  await page.waitForLoadState('networkidle');
  await page.waitForTimeout(500); // Allow animations to settle
}

async function stabilizeVisuals(page: any) {
  // Disable animations and hide variable content
  await page.addStyleTag({
    content: `
      *, *::before, *::after {
        animation-duration: 0s !important;
        transition-duration: 0s !important;
      }
      .loading, .spinner, [data-testid*="loading"] {
        visibility: hidden !important;
      }
    `
  });
}

test.describe('Spacing Visual Tests', () => {
  
  test('All Spacing - light theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-spacing--all-spacing', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-spacing--all-spacing-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('All Spacing - dark theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-spacing--all-spacing', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-spacing--all-spacing-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  test('Semantic Spacing - light theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-spacing--semantic-spacing', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-spacing--semantic-spacing-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('Semantic Spacing - dark theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-spacing--semantic-spacing', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-spacing--semantic-spacing-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  test('Spacing Patterns - light theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-spacing--spacing-patterns', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-spacing--spacing-patterns-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('Spacing Patterns - dark theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-spacing--spacing-patterns', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-spacing--spacing-patterns-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  test('Component Spacing - light theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-spacing--component-spacing', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-spacing--component-spacing-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('Component Spacing - dark theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-spacing--component-spacing', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-spacing--component-spacing-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  test('Usage Guidelines - light theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-spacing--usage-guidelines', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-spacing--usage-guidelines-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('Usage Guidelines - dark theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-spacing--usage-guidelines', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-spacing--usage-guidelines-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
});

// Interactive state tests for key components

