/**
 * Visual Regression Tests for Switch
 * Auto-generated by generate-vrt-baselines.js
 */

import { test, expect } from '@playwright/test';

const STORYBOOK_URL = 'http://localhost:6006';

async function navigateToStory(page: any, storyId: string, theme = 'light') {
  const url = `${STORYBOOK_URL}/iframe.html?id=${storyId}&viewMode=story&theme=${theme}`;
  await page.goto(url);
  await page.waitForLoadState('networkidle');
  await page.waitForTimeout(500); // Allow animations to settle
}

async function stabilizeVisuals(page: any) {
  // Disable animations and hide variable content
  await page.addStyleTag({
    content: `
      *, *::before, *::after {
        animation-duration: 0s !important;
        transition-duration: 0s !important;
      }
      .loading, .spinner, [data-testid*="loading"] {
        visibility: hidden !important;
      }
    `
  });
}

test.describe('Switch Visual Tests', () => {
  
  test('Default - light theme', async ({ page }) => {
    await navigateToStory(page, 'switch--default', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'switch--default-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('Default - dark theme', async ({ page }) => {
    await navigateToStory(page, 'switch--default', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'switch--default-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  test('Checked - light theme', async ({ page }) => {
    await navigateToStory(page, 'switch--checked', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'switch--checked-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('Checked - dark theme', async ({ page }) => {
    await navigateToStory(page, 'switch--checked', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'switch--checked-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  test('Disabled - light theme', async ({ page }) => {
    await navigateToStory(page, 'switch--disabled', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'switch--disabled-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('Disabled - dark theme', async ({ page }) => {
    await navigateToStory(page, 'switch--disabled', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'switch--disabled-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  test('Settings Panel - light theme', async ({ page }) => {
    await navigateToStory(page, 'switch--settings-panel', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'switch--settings-panel-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('Settings Panel - dark theme', async ({ page }) => {
    await navigateToStory(page, 'switch--settings-panel', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'switch--settings-panel-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
});

// Interactive state tests for key components

test.describe('Switch Interactive States', () => {
  test('hover state', async ({ page }) => {
    await navigateToStory(page, 'switch--default');
    await stabilizeVisuals(page);
    
    const element = page.locator('switch').first();
    await element.hover();
    await page.waitForTimeout(100);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'switch--default-hover.png',
      { threshold: 0.2, animations: 'disabled' }
    );
  });
  
  test('focus state', async ({ page }) => {
    await navigateToStory(page, 'switch--default');
    await stabilizeVisuals(page);
    
    const element = page.locator('switch').first();
    await element.focus();
    await page.waitForTimeout(100);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'switch--default-focus.png',
      { threshold: 0.2, animations: 'disabled' }
    );
  });
});
