/**
 * Visual Regression Tests for Token Patterns
 * Auto-generated by generate-vrt-baselines.js
 */

import { test, expect } from '@playwright/test';

const STORYBOOK_URL = 'http://localhost:6006';

async function navigateToStory(page: any, storyId: string, theme = 'light') {
  const url = `${STORYBOOK_URL}/iframe.html?id=${storyId}&viewMode=story&theme=${theme}`;
  await page.goto(url);
  await page.waitForLoadState('networkidle');
  await page.waitForTimeout(500); // Allow animations to settle
}

async function stabilizeVisuals(page: any) {
  // Disable animations and hide variable content
  await page.addStyleTag({
    content: `
      *, *::before, *::after {
        animation-duration: 0s !important;
        transition-duration: 0s !important;
      }
      .loading, .spinner, [data-testid*="loading"] {
        visibility: hidden !important;
      }
    `
  });
}

test.describe('Token Patterns Visual Tests', () => {
  
  test('Typography Patterns - light theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-token-patterns--typography-patterns', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-token-patterns--typography-patterns-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('Typography Patterns - dark theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-token-patterns--typography-patterns', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-token-patterns--typography-patterns-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  test('Color System Patterns - light theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-token-patterns--color-system-patterns', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-token-patterns--color-system-patterns-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('Color System Patterns - dark theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-token-patterns--color-system-patterns', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-token-patterns--color-system-patterns-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  test('Component Patterns - light theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-token-patterns--component-patterns', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-token-patterns--component-patterns-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('Component Patterns - dark theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-token-patterns--component-patterns', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-token-patterns--component-patterns-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  test('Token Implementation Guide - light theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-token-patterns--token-implementation-guide', 'light');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-token-patterns--token-implementation-guide-light.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
  
  test('Token Implementation Guide - dark theme', async ({ page }) => {
    await navigateToStory(page, 'foundations-token-patterns--token-implementation-guide', 'dark');
    await stabilizeVisuals(page);
    
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'foundations-token-patterns--token-implementation-guide-dark.png',
      {
        threshold: 0.2,
        animations: 'disabled'
      }
    );
  });
});

// Interactive state tests for key components

