// Comcast Business Design System - Icon Registry
// High-quality icon management system with proper type support

export interface IconMetadata {
  name: string;
  category: 'navigation' | 'status' | 'communication' | 'data' | 'media' | 'interface' | 'security' | 'general';
  description?: string;
  size?: { width: number; height: number };
  tags?: string[];
}

// Core icon registry with commonly used icons
export const CORE_ICONS = {
  // Navigation
  'chevron': { name: 'chevron', category: 'navigation' as const, description: 'Chevron arrow for navigation' },
  'arrow': { name: 'arrow', category: 'navigation' as const, description: 'Basic arrow' },
  'backarrow': { name: 'backarrow', category: 'navigation' as const, description: 'Back navigation arrow' },
  'doublechevron': { name: 'doublechevron', category: 'navigation' as const, description: 'Double chevron for pagination' },
  'menu': { name: 'menu', category: 'navigation' as const, description: 'Hamburger menu' },
  'globalnav': { name: 'globalnav', category: 'navigation' as const, description: 'Global navigation' },
  
  // Interface
  'close': { name: 'close', category: 'interface' as const, description: 'Close/X button' },
  'check': { name: 'check', category: 'interface' as const, description: 'Checkmark' },
  'plus': { name: 'plus', category: 'interface' as const, description: 'Add/Plus button' },
  'minus': { name: 'minus', category: 'interface' as const, description: 'Remove/Minus button' },
  'search': { name: 'search', category: 'interface' as const, description: 'Search icon' },
  'configure': { name: 'configure', category: 'interface' as const, description: 'Settings/Configure' },
  'refresh': { name: 'refresh', category: 'interface' as const, description: 'Refresh/Reload' },
  'download': { name: 'download', category: 'interface' as const, description: 'Download' },
  'upload': { name: 'upload', category: 'interface' as const, description: 'Upload' },
  'maximize': { name: 'maximize', category: 'interface' as const, description: 'Maximize window' },
  'minimize': { name: 'minimize', category: 'interface' as const, description: 'Minimize window' },
  'sort': { name: 'sort', category: 'interface' as const, description: 'Sort data' },
  'filteralt': { name: 'filteralt', category: 'interface' as const, description: 'Filter' },
  'contextmenu': { name: 'contextmenu', category: 'interface' as const, description: 'Context menu (3 dots)' },
  'grabber': { name: 'grabber', category: 'interface' as const, description: 'Drag handle' },
  
  // Status & Feedback
  'alert': { name: 'alert', category: 'status' as const, description: 'Alert/Warning' },
  'complete': { name: 'complete', category: 'status' as const, description: 'Success/Complete' },
  'bell': { name: 'bell', category: 'status' as const, description: 'Notifications' },
  'notifications': { name: 'notifications', category: 'status' as const, description: 'Notification center' },
  'feedback': { name: 'feedback', category: 'status' as const, description: 'User feedback' },
  
  // Communication
  'chat': { name: 'chat', category: 'communication' as const, description: 'Chat/Message' },
  'message': { name: 'message', category: 'communication' as const, description: 'Message' },
  'conference': { name: 'conference', category: 'communication' as const, description: 'Conference call' },
  'video': { name: 'video', category: 'communication' as const, description: 'Video' },
  'voicemail': { name: 'voicemail', category: 'communication' as const, description: 'Voicemail' },
  
  // Data & Documents
  'document': { name: 'document', category: 'data' as const, description: 'Document' },
  'folder': { name: 'folder', category: 'data' as const, description: 'Folder' },
  'clipboard': { name: 'clipboard', category: 'data' as const, description: 'Clipboard' },
  'analytics': { name: 'analytics', category: 'data' as const, description: 'Analytics/Charts' },
  'report': { name: 'report', category: 'data' as const, description: 'Report' },
  'piechart': { name: 'piechart', category: 'data' as const, description: 'Pie chart' },
  
  // Security
  'blockers': { name: 'blockers', category: 'security' as const, description: 'Security blockers' },
  'password': { name: 'password', category: 'security' as const, description: 'Password' },
  'securityquestion': { name: 'securityquestion', category: 'security' as const, description: 'Security question' },
  'variantlockedtypefilled': { name: 'variantlockedtypefilled', category: 'security' as const, description: 'Locked (filled)' },
  'variantlockedtypeoutline': { name: 'variantlockedtypeoutline', category: 'security' as const, description: 'Locked (outline)' },
  'variantunlockedtypefilled': { name: 'variantunlockedtypefilled', category: 'security' as const, description: 'Unlocked (filled)' },
  'variantunlockedtypeoutline': { name: 'variantunlockedtypeoutline', category: 'security' as const, description: 'Unlocked (outline)' },
  
  // Media
  'avplay': { name: 'avplay', category: 'media' as const, description: 'Play' },
  'avpause': { name: 'avpause', category: 'media' as const, description: 'Pause' },
  'avstop': { name: 'avstop', category: 'media' as const, description: 'Stop' },
  'avrecord': { name: 'avrecord', category: 'media' as const, description: 'Record' },
  'playcircle': { name: 'playcircle', category: 'media' as const, description: 'Play button (circle)' },
  'camera': { name: 'camera', category: 'media' as const, description: 'Camera' },
  
  // Business
  'wallet': { name: 'wallet', category: 'general' as const, description: 'Wallet/Payment' },
  'paymentcard': { name: 'paymentcard', category: 'general' as const, description: 'Payment card' },
  'money': { name: 'money', category: 'general' as const, description: 'Money/Currency' },
  'fees': { name: 'fees', category: 'general' as const, description: 'Fees' },
  'shoppingbag': { name: 'shoppingbag', category: 'general' as const, description: 'Shopping bag' },
  'cartempty': { name: 'cartempty', category: 'general' as const, description: 'Empty cart' },
  'pricetag': { name: 'pricetag', category: 'general' as const, description: 'Price tag' },
  'percent': { name: 'percent', category: 'general' as const, description: 'Percentage' },
  
  // Technology
  'internet': { name: 'internet', category: 'general' as const, description: 'Internet connection' },
  'wifi': { name: 'wifi', category: 'general' as const, description: 'WiFi' },
  'ethernet': { name: 'ethernet', category: 'general' as const, description: 'Ethernet connection' },
  'cloud': { name: 'cloud', category: 'general' as const, description: 'Cloud' },
  'cloudupload': { name: 'cloudupload', category: 'general' as const, description: 'Cloud upload' },
  'device': { name: 'device', category: 'general' as const, description: 'Device' },
  'browser': { name: 'browser', category: 'general' as const, description: 'Browser' },
  'portal': { name: 'portal', category: 'general' as const, description: 'Portal' },
  
  // Users & Account
  'users': { name: 'users', category: 'general' as const, description: 'Users/People' },
  'login': { name: 'login', category: 'general' as const, description: 'Login' },
  'logout': { name: 'logout', category: 'general' as const, description: 'Logout' },
  'switchaccounts': { name: 'switchaccounts', category: 'general' as const, description: 'Switch accounts' },

  // Feather Icons - Communication
  'feather-at-sign': { name: 'feather-at-sign', category: 'communication' as const, description: 'Feather icon: at sign' },
  'feather-bell': { name: 'feather-bell', category: 'communication' as const, description: 'Feather icon: bell' },
  'feather-bell-off': { name: 'feather-bell-off', category: 'communication' as const, description: 'Feather icon: bell off' },
  'feather-headphones': { name: 'feather-headphones', category: 'communication' as const, description: 'Feather icon: headphones' },
  'feather-mail': { name: 'feather-mail', category: 'communication' as const, description: 'Feather icon: mail' },
  'feather-message-circle': { name: 'feather-message-circle', category: 'communication' as const, description: 'Feather icon: message circle' },
  'feather-message-square': { name: 'feather-message-square', category: 'communication' as const, description: 'Feather icon: message square' },
  'feather-mic': { name: 'feather-mic', category: 'communication' as const, description: 'Feather icon: mic' },
  'feather-mic-off': { name: 'feather-mic-off', category: 'communication' as const, description: 'Feather icon: mic off' },
  'feather-phone': { name: 'feather-phone', category: 'communication' as const, description: 'Feather icon: phone' },
  'feather-phone-call': { name: 'feather-phone-call', category: 'communication' as const, description: 'Feather icon: phone call' },
  'feather-phone-forwarded': { name: 'feather-phone-forwarded', category: 'communication' as const, description: 'Feather icon: phone forwarded' },
  'feather-phone-incoming': { name: 'feather-phone-incoming', category: 'communication' as const, description: 'Feather icon: phone incoming' },
  'feather-phone-missed': { name: 'feather-phone-missed', category: 'communication' as const, description: 'Feather icon: phone missed' },
  'feather-phone-off': { name: 'feather-phone-off', category: 'communication' as const, description: 'Feather icon: phone off' },
  'feather-phone-outgoing': { name: 'feather-phone-outgoing', category: 'communication' as const, description: 'Feather icon: phone outgoing' },
  'feather-rss': { name: 'feather-rss', category: 'communication' as const, description: 'Feather icon: rss' },
  'feather-send': { name: 'feather-send', category: 'communication' as const, description: 'Feather icon: send' },
  'feather-speaker': { name: 'feather-speaker', category: 'communication' as const, description: 'Feather icon: speaker' },
  'feather-voicemail': { name: 'feather-voicemail', category: 'communication' as const, description: 'Feather icon: voicemail' },
  'feather-volume': { name: 'feather-volume', category: 'communication' as const, description: 'Feather icon: volume' },
  'feather-volume-1': { name: 'feather-volume-1', category: 'communication' as const, description: 'Feather icon: volume 1' },
  'feather-volume-2': { name: 'feather-volume-2', category: 'communication' as const, description: 'Feather icon: volume 2' },
  'feather-volume-x': { name: 'feather-volume-x', category: 'communication' as const, description: 'Feather icon: volume x' },

  // Feather Icons - Data
  'feather-align-center': { name: 'feather-align-center', category: 'data' as const, description: 'Feather icon: align center' },
  'feather-align-justify': { name: 'feather-align-justify', category: 'data' as const, description: 'Feather icon: align justify' },
  'feather-align-left': { name: 'feather-align-left', category: 'data' as const, description: 'Feather icon: align left' },
  'feather-align-right': { name: 'feather-align-right', category: 'data' as const, description: 'Feather icon: align right' },
  'feather-bar-chart': { name: 'feather-bar-chart', category: 'data' as const, description: 'Feather icon: bar chart' },
  'feather-bar-chart-2': { name: 'feather-bar-chart-2', category: 'data' as const, description: 'Feather icon: bar chart 2' },
  'feather-bold': { name: 'feather-bold', category: 'data' as const, description: 'Feather icon: bold' },
  'feather-clipboard': { name: 'feather-clipboard', category: 'data' as const, description: 'Feather icon: clipboard' },
  'feather-code': { name: 'feather-code', category: 'data' as const, description: 'Feather icon: code' },
  'feather-columns': { name: 'feather-columns', category: 'data' as const, description: 'Feather icon: columns' },
  'feather-database': { name: 'feather-database', category: 'data' as const, description: 'Feather icon: database' },
  'feather-divide': { name: 'feather-divide', category: 'data' as const, description: 'Feather icon: divide' },
  'feather-divide-circle': { name: 'feather-divide-circle', category: 'data' as const, description: 'Feather icon: divide circle' },
  'feather-divide-square': { name: 'feather-divide-square', category: 'data' as const, description: 'Feather icon: divide square' },
  'feather-file': { name: 'feather-file', category: 'data' as const, description: 'Feather icon: file' },
  'feather-file-minus': { name: 'feather-file-minus', category: 'data' as const, description: 'Feather icon: file minus' },
  'feather-file-plus': { name: 'feather-file-plus', category: 'data' as const, description: 'Feather icon: file plus' },
  'feather-file-text': { name: 'feather-file-text', category: 'data' as const, description: 'Feather icon: file text' },
  'feather-folder': { name: 'feather-folder', category: 'data' as const, description: 'Feather icon: folder' },
  'feather-folder-minus': { name: 'feather-folder-minus', category: 'data' as const, description: 'Feather icon: folder minus' },
  'feather-folder-plus': { name: 'feather-folder-plus', category: 'data' as const, description: 'Feather icon: folder plus' },
  'feather-grid': { name: 'feather-grid', category: 'data' as const, description: 'Feather icon: grid' },
  'feather-hard-drive': { name: 'feather-hard-drive', category: 'data' as const, description: 'Feather icon: hard drive' },
  'feather-hash': { name: 'feather-hash', category: 'data' as const, description: 'Feather icon: hash' },
  'feather-italic': { name: 'feather-italic', category: 'data' as const, description: 'Feather icon: italic' },
  'feather-layers': { name: 'feather-layers', category: 'data' as const, description: 'Feather icon: layers' },
  'feather-list': { name: 'feather-list', category: 'data' as const, description: 'Feather icon: list' },
  'feather-pie-chart': { name: 'feather-pie-chart', category: 'data' as const, description: 'Feather icon: pie chart' },
  'feather-server': { name: 'feather-server', category: 'data' as const, description: 'Feather icon: server' },
  'feather-slash': { name: 'feather-slash', category: 'data' as const, description: 'Feather icon: slash' },
  'feather-table': { name: 'feather-table', category: 'data' as const, description: 'Feather icon: table' },
  'feather-terminal': { name: 'feather-terminal', category: 'data' as const, description: 'Feather icon: terminal' },
  'feather-type': { name: 'feather-type', category: 'data' as const, description: 'Feather icon: type' },
  'feather-underline': { name: 'feather-underline', category: 'data' as const, description: 'Feather icon: underline' },

  // Feather Icons - General
  'feather-anchor': { name: 'feather-anchor', category: 'general' as const, description: 'Feather icon: anchor' },
  'feather-aperture': { name: 'feather-aperture', category: 'general' as const, description: 'Feather icon: aperture' },
  'feather-archive': { name: 'feather-archive', category: 'general' as const, description: 'Feather icon: archive' },
  'feather-bluetooth': { name: 'feather-bluetooth', category: 'general' as const, description: 'Feather icon: bluetooth' },
  'feather-book': { name: 'feather-book', category: 'general' as const, description: 'Feather icon: book' },
  'feather-book-open': { name: 'feather-book-open', category: 'general' as const, description: 'Feather icon: book open' },
  'feather-box': { name: 'feather-box', category: 'general' as const, description: 'Feather icon: box' },
  'feather-briefcase': { name: 'feather-briefcase', category: 'general' as const, description: 'Feather icon: briefcase' },
  'feather-calendar': { name: 'feather-calendar', category: 'general' as const, description: 'Feather icon: calendar' },
  'feather-chrome': { name: 'feather-chrome', category: 'general' as const, description: 'Feather icon: chrome' },
  'feather-clock': { name: 'feather-clock', category: 'general' as const, description: 'Feather icon: clock' },
  'feather-cloud': { name: 'feather-cloud', category: 'general' as const, description: 'Feather icon: cloud' },
  'feather-cloud-drizzle': { name: 'feather-cloud-drizzle', category: 'general' as const, description: 'Feather icon: cloud drizzle' },
  'feather-cloud-lightning': { name: 'feather-cloud-lightning', category: 'general' as const, description: 'Feather icon: cloud lightning' },
  'feather-cloud-off': { name: 'feather-cloud-off', category: 'general' as const, description: 'Feather icon: cloud off' },
  'feather-cloud-rain': { name: 'feather-cloud-rain', category: 'general' as const, description: 'Feather icon: cloud rain' },
  'feather-cloud-snow': { name: 'feather-cloud-snow', category: 'general' as const, description: 'Feather icon: cloud snow' },
  'feather-codepen': { name: 'feather-codepen', category: 'general' as const, description: 'Feather icon: codepen' },
  'feather-codesandbox': { name: 'feather-codesandbox', category: 'general' as const, description: 'Feather icon: codesandbox' },
  'feather-coffee': { name: 'feather-coffee', category: 'general' as const, description: 'Feather icon: coffee' },
  'feather-command': { name: 'feather-command', category: 'general' as const, description: 'Feather icon: command' },
  'feather-cpu': { name: 'feather-cpu', category: 'general' as const, description: 'Feather icon: cpu' },
  'feather-credit-card': { name: 'feather-credit-card', category: 'general' as const, description: 'Feather icon: credit card' },
  'feather-delete': { name: 'feather-delete', category: 'general' as const, description: 'Feather icon: delete' },
  'feather-dollar-sign': { name: 'feather-dollar-sign', category: 'general' as const, description: 'Feather icon: dollar sign' },
  'feather-dribbble': { name: 'feather-dribbble', category: 'general' as const, description: 'Feather icon: dribbble' },
  'feather-droplet': { name: 'feather-droplet', category: 'general' as const, description: 'Feather icon: droplet' },
  'feather-facebook': { name: 'feather-facebook', category: 'general' as const, description: 'Feather icon: facebook' },
  'feather-feather': { name: 'feather-feather', category: 'general' as const, description: 'Feather icon: feather' },
  'feather-figma': { name: 'feather-figma', category: 'general' as const, description: 'Feather icon: figma' },
  'feather-framer': { name: 'feather-framer', category: 'general' as const, description: 'Feather icon: framer' },
  'feather-gift': { name: 'feather-gift', category: 'general' as const, description: 'Feather icon: gift' },
  'feather-git-branch': { name: 'feather-git-branch', category: 'general' as const, description: 'Feather icon: git branch' },
  'feather-git-commit': { name: 'feather-git-commit', category: 'general' as const, description: 'Feather icon: git commit' },
  'feather-git-merge': { name: 'feather-git-merge', category: 'general' as const, description: 'Feather icon: git merge' },
  'feather-git-pull-request': { name: 'feather-git-pull-request', category: 'general' as const, description: 'Feather icon: git pull request' },
  'feather-github': { name: 'feather-github', category: 'general' as const, description: 'Feather icon: github' },
  'feather-gitlab': { name: 'feather-gitlab', category: 'general' as const, description: 'Feather icon: gitlab' },
  'feather-globe': { name: 'feather-globe', category: 'general' as const, description: 'Feather icon: globe' },
  'feather-inbox': { name: 'feather-inbox', category: 'general' as const, description: 'Feather icon: inbox' },
  'feather-instagram': { name: 'feather-instagram', category: 'general' as const, description: 'Feather icon: instagram' },
  'feather-layout': { name: 'feather-layout', category: 'general' as const, description: 'Feather icon: layout' },
  'feather-linkedin': { name: 'feather-linkedin', category: 'general' as const, description: 'Feather icon: linkedin' },
  'feather-moon': { name: 'feather-moon', category: 'general' as const, description: 'Feather icon: moon' },
  'feather-package': { name: 'feather-package', category: 'general' as const, description: 'Feather icon: package' },
  'feather-paperclip': { name: 'feather-paperclip', category: 'general' as const, description: 'Feather icon: paperclip' },
  'feather-percent': { name: 'feather-percent', category: 'general' as const, description: 'Feather icon: percent' },
  'feather-pocket': { name: 'feather-pocket', category: 'general' as const, description: 'Feather icon: pocket' },
  'feather-power': { name: 'feather-power', category: 'general' as const, description: 'Feather icon: power' },
  'feather-printer': { name: 'feather-printer', category: 'general' as const, description: 'Feather icon: printer' },
  'feather-shopping-bag': { name: 'feather-shopping-bag', category: 'general' as const, description: 'Feather icon: shopping bag' },
  'feather-shopping-cart': { name: 'feather-shopping-cart', category: 'general' as const, description: 'Feather icon: shopping cart' },
  'feather-sidebar': { name: 'feather-sidebar', category: 'general' as const, description: 'Feather icon: sidebar' },
  'feather-slack': { name: 'feather-slack', category: 'general' as const, description: 'Feather icon: slack' },
  'feather-sun': { name: 'feather-sun', category: 'general' as const, description: 'Feather icon: sun' },
  'feather-sunrise': { name: 'feather-sunrise', category: 'general' as const, description: 'Feather icon: sunrise' },
  'feather-sunset': { name: 'feather-sunset', category: 'general' as const, description: 'Feather icon: sunset' },
  'feather-thermometer': { name: 'feather-thermometer', category: 'general' as const, description: 'Feather icon: thermometer' },
  'feather-toggle-left': { name: 'feather-toggle-left', category: 'general' as const, description: 'Feather icon: toggle left' },
  'feather-toggle-right': { name: 'feather-toggle-right', category: 'general' as const, description: 'Feather icon: toggle right' },
  'feather-tool': { name: 'feather-tool', category: 'general' as const, description: 'Feather icon: tool' },
  'feather-trash': { name: 'feather-trash', category: 'general' as const, description: 'Feather icon: trash' },
  'feather-trash-2': { name: 'feather-trash-2', category: 'general' as const, description: 'Feather icon: trash 2' },
  'feather-trello': { name: 'feather-trello', category: 'general' as const, description: 'Feather icon: trello' },
  'feather-truck': { name: 'feather-truck', category: 'general' as const, description: 'Feather icon: truck' },
  'feather-twitch': { name: 'feather-twitch', category: 'general' as const, description: 'Feather icon: twitch' },
  'feather-twitter': { name: 'feather-twitter', category: 'general' as const, description: 'Feather icon: twitter' },
  'feather-umbrella': { name: 'feather-umbrella', category: 'general' as const, description: 'Feather icon: umbrella' },
  'feather-wind': { name: 'feather-wind', category: 'general' as const, description: 'Feather icon: wind' },
  'feather-youtube': { name: 'feather-youtube', category: 'general' as const, description: 'Feather icon: youtube' },
  'feather-zoom-in': { name: 'feather-zoom-in', category: 'general' as const, description: 'Feather icon: zoom in' },
  'feather-zoom-out': { name: 'feather-zoom-out', category: 'general' as const, description: 'Feather icon: zoom out' },

  // Feather Icons - Interface
  'feather-bookmark': { name: 'feather-bookmark', category: 'interface' as const, description: 'Feather icon: bookmark' },
  'feather-check': { name: 'feather-check', category: 'interface' as const, description: 'Feather icon: check' },
  'feather-check-circle': { name: 'feather-check-circle', category: 'interface' as const, description: 'Feather icon: check circle' },
  'feather-check-square': { name: 'feather-check-square', category: 'interface' as const, description: 'Feather icon: check square' },
  'feather-copy': { name: 'feather-copy', category: 'interface' as const, description: 'Feather icon: copy' },
  'feather-crop': { name: 'feather-crop', category: 'interface' as const, description: 'Feather icon: crop' },
  'feather-download': { name: 'feather-download', category: 'interface' as const, description: 'Feather icon: download' },
  'feather-download-cloud': { name: 'feather-download-cloud', category: 'interface' as const, description: 'Feather icon: download cloud' },
  'feather-edit': { name: 'feather-edit', category: 'interface' as const, description: 'Feather icon: edit' },
  'feather-edit-2': { name: 'feather-edit-2', category: 'interface' as const, description: 'Feather icon: edit 2' },
  'feather-edit-3': { name: 'feather-edit-3', category: 'interface' as const, description: 'Feather icon: edit 3' },
  'feather-external-link': { name: 'feather-external-link', category: 'interface' as const, description: 'Feather icon: external link' },
  'feather-filter': { name: 'feather-filter', category: 'interface' as const, description: 'Feather icon: filter' },
  'feather-flag': { name: 'feather-flag', category: 'interface' as const, description: 'Feather icon: flag' },
  'feather-frown': { name: 'feather-frown', category: 'interface' as const, description: 'Feather icon: frown' },
  'feather-heart': { name: 'feather-heart', category: 'interface' as const, description: 'Feather icon: heart' },
  'feather-link': { name: 'feather-link', category: 'interface' as const, description: 'Feather icon: link' },
  'feather-link-2': { name: 'feather-link-2', category: 'interface' as const, description: 'Feather icon: link 2' },
  'feather-maximize': { name: 'feather-maximize', category: 'interface' as const, description: 'Feather icon: maximize' },
  'feather-maximize-2': { name: 'feather-maximize-2', category: 'interface' as const, description: 'Feather icon: maximize 2' },
  'feather-meh': { name: 'feather-meh', category: 'interface' as const, description: 'Feather icon: meh' },
  'feather-menu': { name: 'feather-menu', category: 'interface' as const, description: 'Feather icon: menu' },
  'feather-minimize': { name: 'feather-minimize', category: 'interface' as const, description: 'Feather icon: minimize' },
  'feather-minimize-2': { name: 'feather-minimize-2', category: 'interface' as const, description: 'Feather icon: minimize 2' },
  'feather-minus': { name: 'feather-minus', category: 'interface' as const, description: 'Feather icon: minus' },
  'feather-minus-circle': { name: 'feather-minus-circle', category: 'interface' as const, description: 'Feather icon: minus circle' },
  'feather-minus-square': { name: 'feather-minus-square', category: 'interface' as const, description: 'Feather icon: minus square' },
  'feather-more-horizontal': { name: 'feather-more-horizontal', category: 'interface' as const, description: 'Feather icon: more horizontal' },
  'feather-more-vertical': { name: 'feather-more-vertical', category: 'interface' as const, description: 'Feather icon: more vertical' },
  'feather-mouse-pointer': { name: 'feather-mouse-pointer', category: 'interface' as const, description: 'Feather icon: mouse pointer' },
  'feather-move': { name: 'feather-move', category: 'interface' as const, description: 'Feather icon: move' },
  'feather-pen-tool': { name: 'feather-pen-tool', category: 'interface' as const, description: 'Feather icon: pen tool' },
  'feather-plus': { name: 'feather-plus', category: 'interface' as const, description: 'Feather icon: plus' },
  'feather-plus-circle': { name: 'feather-plus-circle', category: 'interface' as const, description: 'Feather icon: plus circle' },
  'feather-plus-square': { name: 'feather-plus-square', category: 'interface' as const, description: 'Feather icon: plus square' },
  'feather-refresh-ccw': { name: 'feather-refresh-ccw', category: 'interface' as const, description: 'Feather icon: refresh ccw' },
  'feather-refresh-cw': { name: 'feather-refresh-cw', category: 'interface' as const, description: 'Feather icon: refresh cw' },
  'feather-rotate-ccw': { name: 'feather-rotate-ccw', category: 'interface' as const, description: 'Feather icon: rotate ccw' },
  'feather-rotate-cw': { name: 'feather-rotate-cw', category: 'interface' as const, description: 'Feather icon: rotate cw' },
  'feather-save': { name: 'feather-save', category: 'interface' as const, description: 'Feather icon: save' },
  'feather-scissors': { name: 'feather-scissors', category: 'interface' as const, description: 'Feather icon: scissors' },
  'feather-search': { name: 'feather-search', category: 'interface' as const, description: 'Feather icon: search' },
  'feather-settings': { name: 'feather-settings', category: 'interface' as const, description: 'Feather icon: settings' },
  'feather-share': { name: 'feather-share', category: 'interface' as const, description: 'Feather icon: share' },
  'feather-share-2': { name: 'feather-share-2', category: 'interface' as const, description: 'Feather icon: share 2' },
  'feather-sliders': { name: 'feather-sliders', category: 'interface' as const, description: 'Feather icon: sliders' },
  'feather-smile': { name: 'feather-smile', category: 'interface' as const, description: 'Feather icon: smile' },
  'feather-star': { name: 'feather-star', category: 'interface' as const, description: 'Feather icon: star' },
  'feather-tag': { name: 'feather-tag', category: 'interface' as const, description: 'Feather icon: tag' },
  'feather-thumbs-down': { name: 'feather-thumbs-down', category: 'interface' as const, description: 'Feather icon: thumbs down' },
  'feather-thumbs-up': { name: 'feather-thumbs-up', category: 'interface' as const, description: 'Feather icon: thumbs up' },
  'feather-upload': { name: 'feather-upload', category: 'interface' as const, description: 'Feather icon: upload' },
  'feather-upload-cloud': { name: 'feather-upload-cloud', category: 'interface' as const, description: 'Feather icon: upload cloud' },
  'feather-x': { name: 'feather-x', category: 'interface' as const, description: 'Feather icon: x' },
  'feather-x-circle': { name: 'feather-x-circle', category: 'interface' as const, description: 'Feather icon: x circle' },
  'feather-x-octagon': { name: 'feather-x-octagon', category: 'interface' as const, description: 'Feather icon: x octagon' },
  'feather-x-square': { name: 'feather-x-square', category: 'interface' as const, description: 'Feather icon: x square' },
  'feather-zap': { name: 'feather-zap', category: 'interface' as const, description: 'Feather icon: zap' },
  'feather-zap-off': { name: 'feather-zap-off', category: 'interface' as const, description: 'Feather icon: zap off' },

  // Feather Icons - Media
  'feather-airplay': { name: 'feather-airplay', category: 'media' as const, description: 'Feather icon: airplay' },
  'feather-camera': { name: 'feather-camera', category: 'media' as const, description: 'Feather icon: camera' },
  'feather-camera-off': { name: 'feather-camera-off', category: 'media' as const, description: 'Feather icon: camera off' },
  'feather-cast': { name: 'feather-cast', category: 'media' as const, description: 'Feather icon: cast' },
  'feather-disc': { name: 'feather-disc', category: 'media' as const, description: 'Feather icon: disc' },
  'feather-fast-forward': { name: 'feather-fast-forward', category: 'media' as const, description: 'Feather icon: fast forward' },
  'feather-film': { name: 'feather-film', category: 'media' as const, description: 'Feather icon: film' },
  'feather-image': { name: 'feather-image', category: 'media' as const, description: 'Feather icon: image' },
  'feather-monitor': { name: 'feather-monitor', category: 'media' as const, description: 'Feather icon: monitor' },
  'feather-music': { name: 'feather-music', category: 'media' as const, description: 'Feather icon: music' },
  'feather-pause': { name: 'feather-pause', category: 'media' as const, description: 'Feather icon: pause' },
  'feather-pause-circle': { name: 'feather-pause-circle', category: 'media' as const, description: 'Feather icon: pause circle' },
  'feather-play': { name: 'feather-play', category: 'media' as const, description: 'Feather icon: play' },
  'feather-play-circle': { name: 'feather-play-circle', category: 'media' as const, description: 'Feather icon: play circle' },
  'feather-radio': { name: 'feather-radio', category: 'media' as const, description: 'Feather icon: radio' },
  'feather-repeat': { name: 'feather-repeat', category: 'media' as const, description: 'Feather icon: repeat' },
  'feather-rewind': { name: 'feather-rewind', category: 'media' as const, description: 'Feather icon: rewind' },
  'feather-shuffle': { name: 'feather-shuffle', category: 'media' as const, description: 'Feather icon: shuffle' },
  'feather-skip-back': { name: 'feather-skip-back', category: 'media' as const, description: 'Feather icon: skip back' },
  'feather-skip-forward': { name: 'feather-skip-forward', category: 'media' as const, description: 'Feather icon: skip forward' },
  'feather-smartphone': { name: 'feather-smartphone', category: 'media' as const, description: 'Feather icon: smartphone' },
  'feather-stop-circle': { name: 'feather-stop-circle', category: 'media' as const, description: 'Feather icon: stop circle' },
  'feather-tablet': { name: 'feather-tablet', category: 'media' as const, description: 'Feather icon: tablet' },
  'feather-tv': { name: 'feather-tv', category: 'media' as const, description: 'Feather icon: tv' },
  'feather-video': { name: 'feather-video', category: 'media' as const, description: 'Feather icon: video' },
  'feather-video-off': { name: 'feather-video-off', category: 'media' as const, description: 'Feather icon: video off' },
  'feather-watch': { name: 'feather-watch', category: 'media' as const, description: 'Feather icon: watch' },

  // Feather Icons - Navigation
  'feather-arrow-down': { name: 'feather-arrow-down', category: 'navigation' as const, description: 'Feather icon: arrow down' },
  'feather-arrow-down-circle': { name: 'feather-arrow-down-circle', category: 'navigation' as const, description: 'Feather icon: arrow down circle' },
  'feather-arrow-down-left': { name: 'feather-arrow-down-left', category: 'navigation' as const, description: 'Feather icon: arrow down left' },
  'feather-arrow-down-right': { name: 'feather-arrow-down-right', category: 'navigation' as const, description: 'Feather icon: arrow down right' },
  'feather-arrow-left': { name: 'feather-arrow-left', category: 'navigation' as const, description: 'Feather icon: arrow left' },
  'feather-arrow-left-circle': { name: 'feather-arrow-left-circle', category: 'navigation' as const, description: 'Feather icon: arrow left circle' },
  'feather-arrow-right': { name: 'feather-arrow-right', category: 'navigation' as const, description: 'Feather icon: arrow right' },
  'feather-arrow-right-circle': { name: 'feather-arrow-right-circle', category: 'navigation' as const, description: 'Feather icon: arrow right circle' },
  'feather-arrow-up': { name: 'feather-arrow-up', category: 'navigation' as const, description: 'Feather icon: arrow up' },
  'feather-arrow-up-circle': { name: 'feather-arrow-up-circle', category: 'navigation' as const, description: 'Feather icon: arrow up circle' },
  'feather-arrow-up-left': { name: 'feather-arrow-up-left', category: 'navigation' as const, description: 'Feather icon: arrow up left' },
  'feather-arrow-up-right': { name: 'feather-arrow-up-right', category: 'navigation' as const, description: 'Feather icon: arrow up right' },
  'feather-chevron-down': { name: 'feather-chevron-down', category: 'navigation' as const, description: 'Feather icon: chevron down' },
  'feather-chevron-left': { name: 'feather-chevron-left', category: 'navigation' as const, description: 'Feather icon: chevron left' },
  'feather-chevron-right': { name: 'feather-chevron-right', category: 'navigation' as const, description: 'Feather icon: chevron right' },
  'feather-chevron-up': { name: 'feather-chevron-up', category: 'navigation' as const, description: 'Feather icon: chevron up' },
  'feather-chevrons-down': { name: 'feather-chevrons-down', category: 'navigation' as const, description: 'Feather icon: chevrons down' },
  'feather-chevrons-left': { name: 'feather-chevrons-left', category: 'navigation' as const, description: 'Feather icon: chevrons left' },
  'feather-chevrons-right': { name: 'feather-chevrons-right', category: 'navigation' as const, description: 'Feather icon: chevrons right' },
  'feather-chevrons-up': { name: 'feather-chevrons-up', category: 'navigation' as const, description: 'Feather icon: chevrons up' },
  'feather-compass': { name: 'feather-compass', category: 'navigation' as const, description: 'Feather icon: compass' },
  'feather-corner-down-left': { name: 'feather-corner-down-left', category: 'navigation' as const, description: 'Feather icon: corner down left' },
  'feather-corner-down-right': { name: 'feather-corner-down-right', category: 'navigation' as const, description: 'Feather icon: corner down right' },
  'feather-corner-left-down': { name: 'feather-corner-left-down', category: 'navigation' as const, description: 'Feather icon: corner left down' },
  'feather-corner-left-up': { name: 'feather-corner-left-up', category: 'navigation' as const, description: 'Feather icon: corner left up' },
  'feather-corner-right-down': { name: 'feather-corner-right-down', category: 'navigation' as const, description: 'Feather icon: corner right down' },
  'feather-corner-right-up': { name: 'feather-corner-right-up', category: 'navigation' as const, description: 'Feather icon: corner right up' },
  'feather-corner-up-left': { name: 'feather-corner-up-left', category: 'navigation' as const, description: 'Feather icon: corner up left' },
  'feather-corner-up-right': { name: 'feather-corner-up-right', category: 'navigation' as const, description: 'Feather icon: corner up right' },
  'feather-crosshair': { name: 'feather-crosshair', category: 'navigation' as const, description: 'Feather icon: crosshair' },
  'feather-home': { name: 'feather-home', category: 'navigation' as const, description: 'Feather icon: home' },
  'feather-map': { name: 'feather-map', category: 'navigation' as const, description: 'Feather icon: map' },
  'feather-map-pin': { name: 'feather-map-pin', category: 'navigation' as const, description: 'Feather icon: map pin' },
  'feather-navigation': { name: 'feather-navigation', category: 'navigation' as const, description: 'Feather icon: navigation' },
  'feather-navigation-2': { name: 'feather-navigation-2', category: 'navigation' as const, description: 'Feather icon: navigation 2' },
  'feather-target': { name: 'feather-target', category: 'navigation' as const, description: 'Feather icon: target' },

  // Feather Icons - Security
  'feather-award': { name: 'feather-award', category: 'security' as const, description: 'Feather icon: award' },
  'feather-eye': { name: 'feather-eye', category: 'security' as const, description: 'Feather icon: eye' },
  'feather-eye-off': { name: 'feather-eye-off', category: 'security' as const, description: 'Feather icon: eye off' },
  'feather-log-in': { name: 'feather-log-in', category: 'security' as const, description: 'Feather icon: log in' },
  'feather-log-out': { name: 'feather-log-out', category: 'security' as const, description: 'Feather icon: log out' },
  'feather-user': { name: 'feather-user', category: 'security' as const, description: 'Feather icon: user' },
  'feather-user-check': { name: 'feather-user-check', category: 'security' as const, description: 'Feather icon: user check' },
  'feather-user-minus': { name: 'feather-user-minus', category: 'security' as const, description: 'Feather icon: user minus' },
  'feather-user-plus': { name: 'feather-user-plus', category: 'security' as const, description: 'Feather icon: user plus' },
  'feather-user-x': { name: 'feather-user-x', category: 'security' as const, description: 'Feather icon: user x' },
  'feather-users': { name: 'feather-users', category: 'security' as const, description: 'Feather icon: users' },

  // Feather Icons - Status
  'feather-activity': { name: 'feather-activity', category: 'status' as const, description: 'Feather icon: activity' },
  'feather-alert-circle': { name: 'feather-alert-circle', category: 'status' as const, description: 'Feather icon: alert circle' },
  'feather-alert-octagon': { name: 'feather-alert-octagon', category: 'status' as const, description: 'Feather icon: alert octagon' },
  'feather-alert-triangle': { name: 'feather-alert-triangle', category: 'status' as const, description: 'Feather icon: alert triangle' },
  'feather-battery': { name: 'feather-battery', category: 'status' as const, description: 'Feather icon: battery' },
  'feather-battery-charging': { name: 'feather-battery-charging', category: 'status' as const, description: 'Feather icon: battery charging' },
  'feather-circle': { name: 'feather-circle', category: 'status' as const, description: 'Feather icon: circle' },
  'feather-help-circle': { name: 'feather-help-circle', category: 'status' as const, description: 'Feather icon: help circle' },
  'feather-hexagon': { name: 'feather-hexagon', category: 'status' as const, description: 'Feather icon: hexagon' },
  'feather-info': { name: 'feather-info', category: 'status' as const, description: 'Feather icon: info' },
  'feather-key': { name: 'feather-key', category: 'status' as const, description: 'Feather icon: key' },
  'feather-life-buoy': { name: 'feather-life-buoy', category: 'status' as const, description: 'Feather icon: life buoy' },
  'feather-loader': { name: 'feather-loader', category: 'status' as const, description: 'Feather icon: loader' },
  'feather-lock': { name: 'feather-lock', category: 'status' as const, description: 'Feather icon: lock' },
  'feather-octagon': { name: 'feather-octagon', category: 'status' as const, description: 'Feather icon: octagon' },
  'feather-shield': { name: 'feather-shield', category: 'status' as const, description: 'Feather icon: shield' },
  'feather-shield-off': { name: 'feather-shield-off', category: 'status' as const, description: 'Feather icon: shield off' },
  'feather-square': { name: 'feather-square', category: 'status' as const, description: 'Feather icon: square' },
  'feather-trending-down': { name: 'feather-trending-down', category: 'status' as const, description: 'Feather icon: trending down' },
  'feather-trending-up': { name: 'feather-trending-up', category: 'status' as const, description: 'Feather icon: trending up' },
  'feather-triangle': { name: 'feather-triangle', category: 'status' as const, description: 'Feather icon: triangle' },
  'feather-unlock': { name: 'feather-unlock', category: 'status' as const, description: 'Feather icon: unlock' },
  'feather-wifi': { name: 'feather-wifi', category: 'status' as const, description: 'Feather icon: wifi' },
  'feather-wifi-off': { name: 'feather-wifi-off', category: 'status' as const, description: 'Feather icon: wifi off' },
} as const;

// Type for icon names
export type CoreIconName = keyof typeof CORE_ICONS;

// Get all available icons from the assets directory
export const getAllAvailableIcons = (): string[] => {
  // This would normally be generated at build time
  // For now, we'll return the core icons
  return Object.keys(CORE_ICONS);
};

// Icon utilities
export const getIconMetadata = (name: CoreIconName): IconMetadata => {
  return CORE_ICONS[name];
};

export const getIconsByCategory = (category: IconMetadata['category']): IconMetadata[] => {
  return Object.values(CORE_ICONS).filter(icon => icon.category === category);
};

export const searchIcons = (query: string): IconMetadata[] => {
  const lowercaseQuery = query.toLowerCase();
  return Object.values(CORE_ICONS).filter(icon =>
    icon.name.toLowerCase().includes(lowercaseQuery) ||
    icon.description?.toLowerCase().includes(lowercaseQuery) ||
    icon.category.toLowerCase().includes(lowercaseQuery)
  );
};

// Icon path helper
export const getIconPath = (name: string): string => {
  return `/icons/${name}.svg`;
};

// Preload critical icons
export const CRITICAL_ICONS: CoreIconName[] = [
  'chevron',
  'close',
  'check',
  'plus',
  'minus',
  'search',
  'alert',
  'menu',
  'bell',
  'configure'
];